# Romain Garel - La Roche-Jaudy - Capteur Sonore
---
substitutions:
  name: capteurdb
  
esphome:
  name: ${name}
  name_add_mac_suffix: true
  min_version: 2025.5.0

esp32:
  board: m5stack-atom
  cpu_frequency: 240MHz
  framework:
    type: esp-idf

logger:
api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:

captive_portal:

i2s_audio:
  - id: i2s_audio_bus
    i2s_lrclk_pin: GPIO33
    i2s_bclk_pin: GPIO19

microphone:
  - platform: i2s_audio
    id: echo_microphone
    adc_type: external
    i2s_din_pin: GPIO23
    pdm: true
    sample_rate: 16000
    correct_dc_offset: true

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: Button
    id: echo_button

light:
  - platform: esp32_rmt_led_strip
    id: led
    name: "LED"
    pin: GPIO27
    default_transition_length: 0s
    chipset: SK6812
    num_leds: 1
    rgb_order: grb

sensor:
  - platform: sound_level
    passive: false
    measurement_duration: 1s
    microphone: echo_microphone
    peak:
      name: "Niveau Sonore"
      id: bruit_max
      unit_of_measurement: "dB"
      accuracy_decimals: 1
      filters:
        # Offset de calibration: convertit dBFS en dB SPL
        - offset: 105.0
        - sliding_window_moving_average:
            window_size: 3
            send_every: 1
      on_value:
        then:
          # Rouge : > 85 dB
          - if:
              condition:
                sensor.in_range:
                  id: bruit_max
                  above: 85.0
              then:
                - light.turn_on:
                    id: led
                    red: 100%
                    green: 0%
                    blue: 0%
          # Orange : 80-85 dB
          - if:
              condition:
                sensor.in_range:
                  id: bruit_max
                  above: 80.0
                  below: 85.0
              then:
                - light.turn_on:
                    id: led
                    red: 100%
                    green: 50%
                    blue: 0%
          # Vert : < 80 dB
          - if:
              condition:
                sensor.in_range:
                  id: bruit_max
                  below: 80.0
              then:
                - light.turn_on:
                    id: led
                    red: 0%
                    green: 100%
                    blue: 0%
